### PR TITLE
Application scopes

### PR DESCRIPTION
**Pull request by Lance-Simeon**

### CODE REVIEW

**Review by jeff-simeon — COMMENTED** [review]
Is this integrated into the build?

**Review by jeff-simeon — DISMISSED** [review]

**Review by ashek-simeon — APPROVED** [review]

**Review by jeff-simeon — COMMENTED** [review]
Why does this include a filter change?

**Comment by ashek-simeon** [comment]
> Why does this include a filter change?

it was related to an optimization in the app artur was working on I think

**Comment by jeff-simeon** [comment]
> > Why does this include a filter change?
> 
> it was related to an optimization in the app artur was working on I think

But they come from M365 ci. Why would one be in a manual PR for docs?

**Comment by ashek-simeon** [comment]
> > > Why does this include a filter change?
> > 
> > 
> > it was related to an optimization in the app artur was working on I think
> 
> But they come from M365 ci. Why would one be in a manual PR for docs?

This seems to be a preview to master auto-PR. Did you already notice that?

**Review by jeff-simeon — APPROVED** [review]

**Pull request merged**
